import { config } from 'dotenv'
import path from 'path'
import fs from 'fs'

config({
  path: '.env'
})

const checkEnv = async () => {
  const chalk = (await import('chalk')).default
  if (!fs.existsSync(path.resolve('.env'))) {
    console.log(chalk.red(`Không tìm thấy file môi trường .env`))
    process.exit(1)
  }
}

checkEnv()

const envConfig = {
  // Env DB
  PORT: process.env.PORT,
  DB_NAME: process.env.DB_NAME,
  DB_USERNAME: process.env.DB_USERNAME,
  DB_PASSWORD: process.env.DB_PASSWORD,

  // Collections DB
  DB_USERS_COLLECTION: process.env.DB_USERS_COLLECTION,
  DB_REFRESH_TOKENS_COLLECTION: process.env.DB_REFRESH_TOKENS_COLLECTION,
  DB_BLOGS_COLLECTION: process.env.DB_BLOGS_COLLECTION,
  DB_QUESTIONS_COLLECTION: process.env.DB_QUESTIONS_COLLECTION,
  DB_ANSWERS_COLLECTION: process.env.DB_ANSWERS_COLLECTION,
  DB_REQUESTS_COLLECTION: process.env.DB_REQUESTS_COLLECTION,
  DB_BLOOD_INVENTORY_THRESHOLDS_COLLECTION: process.env.DB_BLOOD_INVENTORY_THRESHOLDS_COLLECTION,
  DB_NOTIFICATIONS_COLLECTION: process.env.DB_NOTIFICATIONS_COLLECTION,
  DB_BLOOD_GROUPS_COLLECTION: process.env.DB_BLOOD_GROUPS_COLLECTION,
  DB_BLOOD_COMPONENTS_COLLECTION: process.env.DB_BLOOD_COMPONENTS_COLLECTION,
  DB_BLOOD_UNITS_COLLECTION: process.env.DB_BLOOD_UNITS_COLLECTION,
  DB_DONATION_REGISTRATIONS_COLLECTION: process.env.DB_DONATION_REGISTRATIONS_COLLECTION,
  DB_DONATION_PROCESSES_COLLECTION: process.env.DB_DONATION_PROCESSES_COLLECTION,
  DB_HEALTH_CHECKS_COLLECTION: process.env.DB_HEALTH_CHECKS_COLLECTION,
  DB_REQUEST_REGISTRATIONS_COLLECTION: process.env.DB_REQUEST_REGISTRATIONS_COLLECTION,
  DB_REQUEST_PROCESSES_COLLECTION: process.env.DB_REQUEST_PROCESSES_COLLECTION,
  DB_REQUEST_PROCESS_DETAILS_COLLECTION: process.env.DB_REQUEST_PROCESS_DETAILS_COLLECTION,
  DB_REQUEST_PROCESS_BLOODS_COLLECTION: process.env.DB_REQUEST_PROCESS_BLOODS_COLLECTION,

  // JWT
  PASSWORD_SECRET: process.env.PASSWORD_SECRET,
  JWT_SECRET_ACCESS_TOKEN: process.env.JWT_SECRET_ACCESS_TOKEN,
  JWT_SECRET_REFRESH_TOKEN: process.env.JWT_SECRET_REFRESH_TOKEN,
  JWT_FORGOT_PASSWORD_TOKEN: process.env.JWT_FORGOT_PASSWORD_TOKEN,
  ACCESS_TOKEN_EXPIRES_IN: process.env.ACCESS_TOKEN_EXPIRES_IN,
  REFRESH_TOKEN_EXPIRES_IN: process.env.REFRESH_TOKEN_EXPIRES_IN,
  FORGOT_PASSWORD_TOKEN_EXPIRES_IN: process.env.REFRESH_TOKEN_EXPIRES_IN
}

export default envConfig
